[project]
name = "fastapibackend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Akash Chaudhari", email = "akashchaudhari1012@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "fastapi>=0.141.1",
    "langgraph>=1.2.11",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
fastapibackend = "app.main:app"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"
module-root = "."

[dependency-groups]
dev = [
    "ruff>=0.16.4",
]
